name: Flutter_Android

on:
  push:
    branches: [main]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
         flutter-version: '2.0.1'


      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore

      - name: Restore packages
        run: flutter pub

      - name: Build Android App Bundle
        run: flutter build app-bundle --release
